// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = "dushenyan"
export const name = "ext-name"
export const version = "0.0.0"
export const displayName = "ext-name"
export const description = undefined
export const extensionId = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandKey = 
  | "ExtName.showHelloWorld"

/**
 * Commands map registed by `dushenyan.ext-name`
 */
export const commands = {
  /**
   * Hello World (Vue): Show
   * @value `ExtName.showHelloWorld`
   */
  extNameShowHelloWorld: "ExtName.showHelloWorld",
} satisfies Record<string, CommandKey>

/**
 * Type union of all configs
 */
export type ConfigKey = never

export interface ConfigKeyTypeMap {
}

export interface ConfigShorthandMap {
}

export interface ConfigShorthandTypeMap {
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
  key: T,
  default: ConfigKeyTypeMap[T],
}


/**
 * Configs map registered by `dushenyan.ext-name`
 */
export const configs = {
}

export interface ScopedConfigKeyTypeMap {
}

export const scopedConfigs = {
  scope: "ext-name",
  defaults: {
  } satisfies ScopedConfigKeyTypeMap,
}

export interface NestedConfigs {
}

export interface NestedScopedConfigs {
}

