// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = "your-username"
export const name = "pkg-name"
export const version = "0.0.1"
export const displayName = "pkg-name"
export const description = "快速创建VS Code扩展模板项目"
export const extensionId = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandKey =
  | "PkgName.showHelloWorld"

/**
 * Commands map registered by `your-username.pkg-name`
 */
export const commands = {
  /**
   * Hello World (Vue): Show
   * @value `PkgName.showHelloWorld`
   */
  pkgNameShowHelloWorld: "PkgName.showHelloWorld",
} satisfies Record<string, CommandKey>

/**
 * Type union of all configs
 */
export type ConfigKey = never

export interface ConfigKeyTypeMap {
}

export interface ConfigShorthandMap {
}

export interface ConfigShorthandTypeMap {
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
  key: T,
  default: ConfigKeyTypeMap[T],
}


/**
 * Configs map registered by `your-username.pkg-name`
 */
export const configs = {
}

export interface ScopedConfigKeyTypeMap {
}

export const scopedConfigs = {
  scope: "pkg-name",
  defaults: {
  } satisfies ScopedConfigKeyTypeMap,
}

export interface NestedConfigs {
}

export interface NestedScopedConfigs {
}

